title: "Nkouka Leko Edhi Messages"
description: "Portfolio de Nkouka Leko Edhi Messages — Computer Engineering Student, Full-Stack Developer & Creative Technologist."
url: "https://eddhynkoukaleko-web.github.io"
baseurl: "/Nkouka-Leko-Edhi-Messages"

theme: null

markdown: kramdown

plugins: []
